### ISSUE TITLE
How to use the filter expression like $.objects[?(@some_field > 5)]

### ISSUE THREAD

**Issue by iwanglian** [sileht/python-jsonpath-rw-ext#15]
In the doc, there are 3 example of filter , how to use the first one?

$.objects[?(@some_field > 5)]
$.objects[?some_field = "foobar")]
$.objects[?some_field > 5 & other < 2)]

**Comment by ivanli1990** [comment]
I meet this issue too. I don't know how to use 'Extensions'. Examples could not be easy to understand.
