### ISSUE TITLE
KeyError when applying filter

### ISSUE THREAD

**Issue by VictoryShima** [sileht/python-jsonpath-rw-ext#2]
Hello,

I just found out about your package and tried to test this code: 
```python
import jsonpath_rw_ext
jsonpath_rw_ext.parse('foo[*][?(@.baz==1)]').find( {'foo': [{'baz': 1}, {'baz': 2}]} )
```

But I receive a KeyError. Could you check this out?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jsonpath_rw/jsonpath.py", line 228, in find
    for submatch in self.right.find(subdata)]
  File "/usr/lib/python2.7/site-packages/jsonpath_rw_ext/_filter.py", line 47, in find
    self.expressions))))]
  File "/usr/lib/python2.7/site-packages/jsonpath_rw_ext/_filter.py", line 46, in <lambda>
    len(list(filter(lambda x: x.find(datum.value[i]),
KeyError: 0
```

PS: thank you a lot for having the initiative to develop these jsonpath extensions =)

**Comment by sileht** [comment]
You should use 'foo[?(@.baz==1)]' to find [{'baz': 1}] from {'foo': [{'baz': 1}, {'baz': 2}]}

Or the data must be {'foo': [[{'baz': 1}, {'baz': 2}]]} (notes the double list) to 'foo[*][?(@.baz==1)]' to find [{'baz': 1}]

Anyways the code shouldn't raise an exception but just return an empty list. I have fixed that here:

https://github.com/sileht/python-jsonpath-rw-ext/commit/da3e74d4ffd5ca11faad6b0a3c76356a51e2cf28
