### ISSUE TITLE
requirements.txt 

### ISSUE THREAD

**Issue by coreycb** [sileht/python-jsonpath-rw-ext#3]
I ran into an issue while packaging 0.1.9 for Debian/Ubuntu.  There are 2 tests that fail if jsonpath_rw is at 1.2.0.  To recreate, update requirements.txt with jsonpath_rw==1.2.0 and run the py27 tests.  I was able to recreate on the master branch.

The failing tests: http://paste.ubuntu.com/13800990/

Can you update requirements.txt with the min version of jsonpath_rw that's required?  It currently doesn't specify a min version.

**Comment by sileht** [comment]
Thanks! I have fixed the issue: https://github.com/sileht/python-jsonpath-rw-ext/commit/4c667b8643df371d6e1fde07d593637d9ea089ca

**Comment by coreycb** [comment]
Thanks!
