### ISSUE TITLE
Unable to filter on values that are floating point.

### ISSUE THREAD

**Issue by 0xdecaf** [sileht/python-jsonpath-rw-ext#4]
```javascript
[
  {"outcome": "Good", "confidence": 0.48},
  {"outcome": "Bad", "confidence": 0.52},
]
```

$[?(@.confidence > 0.5)]

**Exception: Parse error at 1:21 near token . (.)**

The following code parses correctly but does not work properly because the comparison is with an int and a float.  What's odd is that a >= comparison does return something but just > does not.
$[?(@.confidence > 0)]

My theory is that this is due to the lexer in jsonpath-rw.  the NUMBER token might at fault here in that it specifies only digits are allowed.  I can't quite tell if this is designed for something else other than filter predicates.

```python
    def t_NUMBER(self, t):
        r'-?\d+'
        t.value = int(t.value)
        return t
```

_Note: I am filing this bug here as the filter functionality is the only thing affected by this that I know of._

**Comment by 0xdecaf** [comment]
Any word on integrating my pull request to fix this issue?

**Comment by sileht** [comment]
I have fixed the pep8 of your PR, and merged it.
